### ISSUE TITLE
Profile picture is cut off

### ISSUE THREAD

**Issue by GlennRen** [2016rshah/2016rshah.github.io#11]
On my laptop (1366x768) the profile picture is cut off but when I switch to a monitor it seems fine. I'm thinking it's a problem with the padding on the container?

**Comment by 2016rshah** [comment]
Example:
![cut_off_image](https://cloud.githubusercontent.com/assets/6821244/12022964/a0efc8b4-ad62-11e5-9aa8-2bb2d4065aa6.jpg)

**Comment by 2016rshah** [comment]
[Fixed it](https://github.com/2016rshah/blog/commit/f4f8fdf34de0f61111147226de5d1b69b66ac1b3)
