### ISSUE TITLE
About link --> rshah.io

### ISSUE THREAD

**Issue by GlennRen** [2016rshah/2016rshah.github.io#12]
I wasn't sure if you kept it the same on purpose or you just forgot to change it but it redirects to rshah.io (old site?) which seems empty.

**Comment by 2016rshah** [comment]
[Fixed it](https://github.com/2016rshah/blog/commit/fa8c1e51ed71123024948a251daf285c71724533), sorry about that! Thanks for letting me know, I just missed that link when I updated my URL
